[Unit]
Wants=tailscaled.service
After=tailscaled.service

[Service]
EnvironmentFile=/etc/caddy/netlify.env
ExecStartPre=
ExecStartPre=/usr/local/bin/caddy-netlify validate --config /etc/caddy/Caddyfile
ExecStart=
ExecStart=/usr/local/bin/caddy-netlify run --config /etc/caddy/Caddyfile
ExecReload=
ExecReload=/usr/local/bin/caddy-netlify reload --config /etc/caddy/Caddyfile --force
Restart=on-failure
RestartSec=5s
